---
- hosts: "{{ target_group | default('local') }}"
  become: yes

  vars_files:
    - ./../vars.yml  

  roles:
    # we need to interact with docker via ansible
    # https://galaxy.ansible.com/geerlingguy/docker
    - geerlingguy.docker
    - geerlingguy.pip

  tasks:
    - name: booyah
      command: docker -v
      register: dockerVersion

    - debug: msg="{{dockerVersion.stdout}}"